swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection by Robotnik
  description: |
    <h1>HTML Injection PoC by Robotnik</h1>

    ![aa](https://hd2.tudocdn.net/1139888)

    This image was injected into Swagger using Markdown syntax.
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
