swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: onload="alert(1)" <iframe srcdoc="<script>alert(1)</script>"></iframe>
  /:
    get:
      responses:
        200:
          description: Successful response
